kind: ConfigMap
apiVersion: v1
metadata:
  namespace: ubuntu
  name: fileserver-as3-configmap
  labels:
    f5type: virtual-server
    as3: "true" # set to true to process this configMap. For staging set to false.
data:
 template: |
   {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.13.0",
            "id": "urn:uuid:33045210-3ab8-4636-9b2a-c98d22ab915d",
            "fileserver_partition": {
                "class": "Tenant",
                "fileserver_app": {
                    "class": "Application",
                    "template": "generic",
                    "fileserver_ssh_service": {
                        "class": "Service_TCP",
                        "virtualAddresses": [
                            "10.0.2.100",
                            "10.0.2.101"
                        ],
                        "virtualPort": 22,
                        "pool": "fileserver_ssh_pool"
                    },
                    "fileserver_ssh_pool": {
                        "class": "Pool",
                        "monitors": [
                            "tcp"
                        ],
                        "members": [
                            {
                                "servicePort": 22,
                                "serverAddresses": []
                            }
                        ]
                    }
                }
            }
        }
    }
