apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
  namespace: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
     #annotations:
       #prometheus.io/scrape: "true"
       #prometheus.io/port: "9113"
    spec:
      containers:
      - image: michaelwoleary/ubuntu:1.3
        imagePullPolicy: Always
        name: ubuntu
        command: ["/usr/sbin/sshd","-D"]
        ports:
        - name: ssh
          containerPort: 22
