apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
  namespace: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
     #annotations:
       #prometheus.io/scrape: "true"
       #prometheus.io/port: "9113"
    spec:
      containers:
      - image: ubuntu #or your image here
        imagePullPolicy: Always
        name: ubuntu
        command: ["/bin/sleep", "3650d"]
        ports:
        - name: ssh
          containerPort: 22
